name: Trigger homepage

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  trigger-homepage:
    runs-on: ubuntu-latest
    steps:
    - name: post to webhook
      run: |
        curl \
          -X POST -u ${{ secrets.PAT_USERNAME}}:${{secrets.PAT_TOKEN}} \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/tretoen/homepage/dispatches \
          -d '{"event_type":"update_submodules"}'
